import type {
  MuzaBusinessModel,
  MuzaIndustryPlaybook,
} from '@/types/muza-industry-playbook'

/**
 * Universal foundational playbooks for the 10 Mūza business models.
 * Provides general domain understanding and strategic principles for each model.
 */
export const MUZA_INDUSTRY_PLAYBOOKS: Record<
  MuzaBusinessModel,
  MuzaIndustryPlaybook
> = {
  LOCAL_SERVICE: {
    id: 'base-local-service',
    industry: 'Local Services',
    subindustries: [
      'Hairdressing & Barber',
      'Beauty & Aesthetics',
      'Pet Grooming',
      'Photography',
      'Home & Garden Maintenance',
    ],
    businessModel: 'LOCAL_SERVICE',
    typicalObjectives: [
      'Increase local appointment bookings',
      'Build client loyalty and repeat visits',
      'Enhance local reputation and word-of-mouth',
      'Fill empty calendar time slots',
    ],
    customerDecisionFactors: [
      'Geographic proximity and accessibility',
      'Customer reviews and star ratings',
      'Visual proof of work quality',
      'Pricing transparency',
      'Ease of booking',
    ],
    trustDrivers: [
      'Authentic before-and-after transformations',
      'Verified customer testimonials',
      'Professional credentials and hygiene standards',
      'Consistent service experience',
    ],
    conversionActions: [
      'Online appointment booking',
      'Direct phone enquiry',
      'Instant messaging / DM enquiry',
      'Website contact form submission',
    ],
    contentPillars: [
      'Behind-the-scenes & service process',
      'Client transformations & portfolio',
      'Expert maintenance tips & advice',
      'Local community & team highlights',
    ],
    usefulProof: [
      'Before and after photos',
      'Video demonstrations of service',
      'Customer reviews & ratings',
      'Certifications & qualifications',
    ],
    commonObjections: [
      'Is the pricing justified for the quality?',
      'Can I trust the provider with my expectations?',
      'Is the location and schedule convenient for me?',
      'What happens if I am dissatisfied with the result?',
    ],
    seasonalFactors: [
      'Demand surges before holidays and celebrations',
      'Seasonal shifts in service needs',
      'Weather impact on outdoor local services',
    ],
    localVisibilityImportance: 'HIGH',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Instagram',
      'Google Business Profile',
      'Facebook',
      'Website',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'INSTAGRAM_POST',
      'GOOGLE_BUSINESS_PROFILE',
      'INSTAGRAM_CAROUSEL',
    ],
    strategicOpportunities: [
      'Capitalize on local search intent via Google Business Profile',
      'Establish client loyalty or recurring appointment routines',
      'Partner with non-competing complementary local businesses',
    ],
    strategicRisks: [
      'Neglecting Google Business Profile and customer review responses',
      'Over-promising results on visual transformations',
      'Failing to implement systemized retention for one-time clients',
    ],
  },

  HOSPITALITY: {
    id: 'base-hospitality',
    industry: 'Hospitality & Accommodation',
    subindustries: [
      'Hotels',
      'Bed & Breakfast',
      'Vacation Rentals',
      'Guesthouses',
      'Campsites',
    ],
    businessModel: 'HOSPITALITY',
    typicalObjectives: [
      'Maximize direct website bookings',
      'Increase average stay duration',
      'Fill off-peak and mid-week availability',
      'Promote unique local destination experiences',
    ],
    customerDecisionFactors: [
      'Destination appeal and location convenience',
      'Guest reviews and host reputation',
      'Room comfort and property amenities',
      'Booking flexibility and fair pricing',
      'Unique atmosphere and charm',
    ],
    trustDrivers: [
      'High-quality authentic property photos',
      'Detailed recent guest reviews',
      'Clear cancellation and house policies',
      'Responsive and welcoming communication',
    ],
    conversionActions: [
      'Direct website reservation',
      'Availability inquiry',
      'Special package booking',
      'Newsletter subscription for special offers',
    ],
    contentPillars: [
      'Destination highlights & local secret spots',
      'Guest experience & room showcases',
      'Seasonal itineraries & activities',
      'Host storytelling & hospitality ethos',
    ],
    usefulProof: [
      'Verified guest review quotes & ratings',
      'High-resolution property and room photos',
      'Awards & eco-label certifications',
      'Video room tours & walkthroughs',
    ],
    commonObjections: [
      'Do the photos accurately represent the actual property?',
      'Is the location quiet and easily accessible?',
      'Are there hidden cleaning or amenity fees?',
      'How flexible is the cancellation policy?',
    ],
    seasonalFactors: [
      'High summer and end-of-year holiday peaks',
      'Off-peak low occupancy shoulder seasons',
      'School holiday calendar fluctuations',
      'Local regional events and festival dates',
    ],
    localVisibilityImportance: 'HIGH',
    seoImportance: 'HIGH',
    recommendedChannels: [
      'Instagram',
      'Website',
      'Google Business Profile',
      'Facebook',
      'Email',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'WEBSITE_PAGE',
      'INSTAGRAM_CAROUSEL',
      'BLOG_ARTICLE',
    ],
    strategicOpportunities: [
      'Highlight unique local destination experiences to attract travelers',
      'Drive direct website bookings to reduce third-party OTA commissions',
      'Create curated seasonal weekend getaway packages',
    ],
    strategicRisks: [
      'Over-dependence on online travel agency (OTA) platforms',
      'Ignoring seasonal content planning during low-demand months',
      'Misalignment between promotional visuals and actual guest experience',
    ],
  },

  RETAIL: {
    id: 'base-retail',
    industry: 'Physical Retail',
    subindustries: [
      'Boutiques & Apparel',
      'Concept Stores',
      'Bookstores',
      'Specialty Retail Outlets',
      'Local Lifestyle Shops',
    ],
    businessModel: 'RETAIL',
    typicalObjectives: [
      'Drive foot traffic to the physical store',
      'Increase average basket value',
      'Promote new collection arrivals',
      'Build a loyal local customer community',
    ],
    customerDecisionFactors: [
      'Store location and ease of access',
      'Curated product selection and uniqueness',
      'In-store ambiance and shopping experience',
      'Staff advice and attentive service',
    ],
    trustDrivers: [
      'Transparent product curation & origins',
      'Welcoming and inspiring in-store atmosphere',
      'Positive local customer reviews',
      'Clear exchange and return policies',
    ],
    conversionActions: [
      'In-store visit',
      'In-store event attendance',
      'Click-and-collect item reservation',
      'Phone product stock inquiry',
    ],
    contentPillars: [
      'New arrivals & product styling guides',
      'In-store experience & store atmosphere',
      'Behind-the-scenes & staff picks',
      'Special events & local promotions',
    ],
    usefulProof: [
      'Customer styling lookbooks & photos',
      'Staff product recommendations & reviews',
      'Store ambiance videos & virtual tours',
      'Supplier craftsmanship stories',
    ],
    commonObjections: [
      'Is the item currently available in store stock?',
      'Are prices competitive compared to online options?',
      'What are the exact store opening hours?',
      'Is parking or public transport convenient?',
    ],
    seasonalFactors: [
      'Holiday season shopping volume spikes',
      'New season collection arrivals',
      'Summer and winter clearance sales',
      'Local neighborhood shopping events',
    ],
    localVisibilityImportance: 'HIGH',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Instagram',
      'Google Business Profile',
      'Facebook',
      'Website',
    ],
    usefulContentFormats: [
      'INSTAGRAM_CAROUSEL',
      'INSTAGRAM_STORY',
      'INSTAGRAM_REEL',
      'GOOGLE_BUSINESS_PROFILE',
    ],
    strategicOpportunities: [
      'Host exclusive in-store workshops or private shopping evenings',
      'Leverage Google Business Profile product listings for local discovery',
      'Create curated gift guides for local holiday shopping',
    ],
    strategicRisks: [
      'Failing to keep local store hours and availability updated online',
      'Relying solely on digital posts without driving physical store visits',
      'Posting generic product photos without personal advice or curation',
    ],
  },

  ECOMMERCE: {
    id: 'base-ecommerce',
    industry: 'E-Commerce',
    subindustries: [
      'Online Fashion & Accessories',
      'Direct-to-Consumer Brands',
      'Specialty Online Stores',
      'Digital Native Products',
    ],
    businessModel: 'ECOMMERCE',
    typicalObjectives: [
      'Increase website checkout conversion rate',
      'Drive targeted organic and referral traffic',
      'Lower customer acquisition costs (CAC)',
      'Improve customer retention and reorder rate',
    ],
    customerDecisionFactors: [
      'Clear product utility and benefit presentation',
      'Shipping costs and delivery speed',
      'Customer reviews and social proof',
      'Hassle-free return policy',
      'Website security and checkout ease',
    ],
    trustDrivers: [
      'Verified customer ratings and review photos',
      'Secure payment badges and guarantees',
      'Transparent return & refund policy',
      'Real product unboxing and demonstration videos',
    ],
    conversionActions: [
      'Online cart checkout completion',
      'Email list subscription for launch/discount',
      'Wishlist item creation',
      'Product page interaction',
    ],
    contentPillars: [
      'Product benefits & demonstration guides',
      'Customer unboxing & user reviews',
      'Brand origin & ethical values',
      'Promotional offers & product launches',
    ],
    usefulProof: [
      'User-generated content (UGC)',
      'Customer rating summary badges',
      'Product comparison tables',
      'Detailed material/ingredient breakdowns',
    ],
    commonObjections: [
      'Will the physical product match the website photos?',
      'How fast and expensive is international/domestic shipping?',
      'How easy is it to process a return if dissatisfied?',
      'Is this online store legitimate and secure?',
    ],
    seasonalFactors: [
      'Black Friday & Cyber Monday sales events',
      'Q4 holiday shopping peak',
      'End-of-season inventory clearance',
      'New collection product launch cycles',
    ],
    localVisibilityImportance: 'LOW',
    seoImportance: 'HIGH',
    recommendedChannels: [
      'Instagram',
      'TikTok',
      'Website',
      'Email',
      'Blog',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'TIKTOK',
      'INSTAGRAM_CAROUSEL',
      'BLOG_ARTICLE',
      'WEBSITE_PAGE',
    ],
    strategicOpportunities: [
      'Implement automated post-purchase email flows to boost reorders',
      'Leverage short-form video for authentic product demonstrations',
      'Optimize product pages for high-intent long-tail search keywords',
    ],
    strategicRisks: [
      'High advertising spend without optimizing website conversion rate',
      'Excessive checkout friction causing high cart abandonment',
      'Neglecting post-purchase customer relationships and review capture',
    ],
  },

  PROFESSIONAL_SERVICE: {
    id: 'base-professional-service',
    industry: 'Professional Services',
    subindustries: [
      'Consulting & Strategy',
      'Accounting & Legal',
      'Architecture & Engineering',
      'Marketing & Design Agencies',
    ],
    businessModel: 'PROFESSIONAL_SERVICE',
    typicalObjectives: [
      'Generate qualified inbound business leads',
      'Establish domain authority and industry leadership',
      'Increase average contract value',
      'Shorten sales negotiation cycles',
    ],
    customerDecisionFactors: [
      'Demonstrated domain expertise and track record',
      'Relevance of past client case studies',
      'Professional reputation and peer trust',
      'Clarity of methodology and communication',
    ],
    trustDrivers: [
      'Detailed client case studies showing concrete results',
      'Endorsements and testimonials from reputable clients',
      'Published thought leadership and insights',
      'Transparent working process and pricing structure',
    ],
    conversionActions: [
      'Discovery call booking',
      'Lead magnet resource download',
      'Detailed proposal request',
      'Contact form submission',
    ],
    contentPillars: [
      'Industry insights & strategic breakdowns',
      'Client case studies & problem-solving recaps',
      'Frameworks & methodology explanations',
      'Thought leadership & expert commentary',
    ],
    usefulProof: [
      'Client testimonials & detailed case studies',
      'Quantifiable outcome metrics',
      'Professional certifications & industry awards',
      'Whitepapers & educational articles',
    ],
    commonObjections: [
      'Is the financial ROI justified for our business?',
      'Does the provider understand our industry context?',
      'How much internal time will our team need to commit?',
      'What differentiates this provider from competitors?',
    ],
    seasonalFactors: [
      'Fiscal year budget planning cycles',
      'Q1 strategy kickoffs and Q4 goal pushes',
      'Summer executive decision-making slowdown',
    ],
    localVisibilityImportance: 'LOW',
    seoImportance: 'HIGH',
    recommendedChannels: [
      'LinkedIn',
      'Website',
      'Blog',
      'Email',
      'YouTube',
    ],
    usefulContentFormats: [
      'LINKEDIN_POST',
      'BLOG_ARTICLE',
      'WEBSITE_PAGE',
      'INSTAGRAM_CAROUSEL',
    ],
    strategicOpportunities: [
      'Publish detailed breakdown case studies showing problem-solution-impact',
      'Optimize LinkedIn profiles and company pages for lead capture',
      'Create high-value educational resources for targeted decision-makers',
    ],
    strategicRisks: [
      'Using overly complex industry jargon that alienates prospective clients',
      'Publishing generic advice without proprietary methodology or insight',
      'Inconsistent content publishing that undermines perceived reliability',
    ],
  },

  CREATOR_EXPERT: {
    id: 'base-creator-expert',
    industry: 'Creator & Expert Business',
    subindustries: [
      'Coaching & Mentoring',
      'Online Training & Education',
      'Content Creators & Authors',
      'Keynote Speakers & Thought Leaders',
    ],
    businessModel: 'CREATOR_EXPERT',
    typicalObjectives: [
      'Grow an engaged audience and brand community',
      'Sell courses, coaching programs, or digital products',
      'Build personal authority in a specific domain',
      'Generate a consistent lead flow for digital offers',
    ],
    customerDecisionFactors: [
      'Personal alignment and trust in the creator',
      'Clarity of the promised personal or professional transformation',
      'Proof of student or client success stories',
      'Quality and value of free educational content',
    ],
    trustDrivers: [
      'Authentic personal story and journey',
      'Student or client transformation proof',
      'Consistent high-value educational content',
      'Active community engagement and responsiveness',
    ],
    conversionActions: [
      'Email newsletter subscription',
      'Webinar or masterclass registration',
      'Course or digital product purchase',
      'Coaching program application',
    ],
    contentPillars: [
      'Actionable educational advice & how-tos',
      'Transformation stories & student results',
      'Personal journey & behind-the-scenes',
      'Mindset & strategic frameworks',
    ],
    usefulProof: [
      'Student transformation interviews & case studies',
      'Mini-lesson video clips & screen walkthroughs',
      'Community feedback & review screenshots',
      'Personal track record and achievements',
    ],
    commonObjections: [
      'Will this transformation work for my specific situation?',
      'Do I have enough time to follow this program?',
      'Is the expert genuine and experienced?',
      'Does the price match the expected value?',
    ],
    seasonalFactors: [
      'New Year personal growth & resolution surge',
      'September back-to-school learning mindset',
      'Summer seasonal engagement shifts',
    ],
    localVisibilityImportance: 'LOW',
    seoImportance: 'HIGH',
    recommendedChannels: [
      'Instagram',
      'YouTube',
      'LinkedIn',
      'Email',
      'TikTok',
      'Blog',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'YOUTUBE_SHORT',
      'LINKEDIN_POST',
      'INSTAGRAM_CAROUSEL',
      'BLOG_ARTICLE',
    ],
    strategicOpportunities: [
      'Build an owned email subscriber list independent of social algorithms',
      'Repurpose long-form video or written content into short-form assets',
      'Develop high-converting lead magnet funnels for digital products',
    ],
    strategicRisks: [
      'Creator burnout due to unsustainable content creation pace',
      'Relying exclusively on social platforms without email list ownership',
      'Over-promising quick transformation results that damage trust',
    ],
  },

  FOOD_BEVERAGE: {
    id: 'base-food-beverage',
    industry: 'Food & Beverage',
    subindustries: [
      'Restaurants',
      'Cafes & Coffee Shops',
      'Bars & Bistros',
      'Bakeries & Patisseries',
      'Catering & Food Trucks',
    ],
    businessModel: 'FOOD_BEVERAGE',
    typicalObjectives: [
      'Increase table reservations and walk-in foot traffic',
      'Promote signature dishes & seasonal menus',
      'Build local customer dining loyalty',
      'Fill low-traffic weekday lunch/dinner slots',
    ],
    customerDecisionFactors: [
      'Food visual appeal and culinary quality',
      'Location convenience and ease of access',
      'Atmosphere, decor, and ambiance',
      'Customer ratings and review feedback',
      'Price range and menu diversity',
    ],
    trustDrivers: [
      'Appetizing, authentic food photos & videos',
      'Fresh local ingredient sourcing highlights',
      'Consistently high ratings on local search & review sites',
      'Clean, welcoming dining room environment',
    ],
    conversionActions: [
      'Table reservation booking',
      'Takeaway or online delivery order',
      'Special event or group booking inquiry',
      'Directions search / immediate store visit',
    ],
    contentPillars: [
      'Signature dishes & seasonal menu updates',
      'Kitchen behind-the-scenes & culinary process',
      'Ambiance & dining room experience',
      'Events, specials & chef announcements',
    ],
    usefulProof: [
      'High-quality food photography & short videos',
      'Customer review quotes & ratings',
      'Supplier & local ingredient origin stories',
      'Chef background & culinary passion',
    ],
    commonObjections: [
      'Is the food fresh and prepared with quality ingredients?',
      'Do I need an advance reservation to get a table?',
      'Are there dietary options (e.g. vegetarian, gluten-free)?',
      'What is the typical price per person?',
    ],
    seasonalFactors: [
      'Summer outdoor terrace dining peaks',
      'End-of-year festive celebration bookings',
      'Special holiday dining nights (e.g. Valentine’s Day)',
      'Weather conditions impacting walk-in foot traffic',
    ],
    localVisibilityImportance: 'HIGH',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Instagram',
      'Google Business Profile',
      'Facebook',
      'TikTok',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'INSTAGRAM_POST',
      'GOOGLE_BUSINESS_PROFILE',
      'INSTAGRAM_STORY',
    ],
    strategicOpportunities: [
      'Use short video content to showcase food preparation and plating',
      'Maintain an up-to-date Google Business Profile with menu & hours',
      'Create special mid-week promotional dining experiences',
    ],
    strategicRisks: [
      'Using stock photos instead of real prepared dishes',
      'Neglecting online customer reviews on Google and maps platforms',
      'Irregular social posting during high-demand dining hours',
    ],
  },

  HEALTH_WELLNESS: {
    id: 'base-health-wellness',
    industry: 'Health & Wellness',
    subindustries: [
      'Spas & Relaxation',
      'Massage Therapy',
      'Yoga & Pilates Studios',
      'Sophrology & Relaxation',
      'Naturopathy & Holistic Care',
    ],
    businessModel: 'HEALTH_WELLNESS',
    typicalObjectives: [
      'Increase session and class bookings',
      'Build customer trust and emotional reassurance',
      'Promote session packages and membership routines',
      'Educate on wellness benefits and self-care',
    ],
    customerDecisionFactors: [
      'Practitioner empathy, listening and professionalism',
      'Serene, clean and welcoming environment',
      'Client review feedback and recommendations',
      'Clarity of service offering and pricing',
      'Location convenience and peaceful setting',
    ],
    trustDrivers: [
      'Practitioner credentials and practice history',
      'Client testimonials focused on comfort and wellbeing',
      'Transparent descriptions of session walkthroughs',
      'Clean, calming studio visuals',
    ],
    conversionActions: [
      'Online session or class booking',
      'Discovery call / initial consultation enquiry',
      'Trial class or package signup',
      'Gift voucher purchase',
    ],
    contentPillars: [
      'Wellness advice & daily self-care routines',
      'Studio environment & session experience',
      'Practitioner approach & wellness philosophy',
      'Client relaxation journeys & experiences',
    ],
    usefulProof: [
      'Client testimonials on overall experience and comfort',
      'Studio ambiance photos & serene video walkthroughs',
      'Practitioner qualifications & training background',
      'Step-by-step session expectations guide',
    ],
    commonObjections: [
      'Will I feel comfortable and at ease during the session?',
      'Is this service suitable for beginners?',
      'What exactly happens during a first appointment?',
      'Are the practitioners properly certified?',
    ],
    seasonalFactors: [
      'New Year wellness & self-care resolutions',
      'Spring energy renewal & relaxation demand',
      'Pre-holiday stress relief demand surge',
    ],
    localVisibilityImportance: 'HIGH',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Instagram',
      'Google Business Profile',
      'Website',
      'Facebook',
    ],
    usefulContentFormats: [
      'INSTAGRAM_CAROUSEL',
      'INSTAGRAM_REEL',
      'WEBSITE_PAGE',
      'GOOGLE_BUSINESS_PROFILE',
    ],
    strategicOpportunities: [
      'Create soothing studio video tours to reduce first-time appointment anxiety',
      'Offer introductory trial packages for local residents',
      'Publish educational self-care content for routine maintenance',
    ],
    strategicRisks: [
      'Making inappropriate medical, diagnostic or therapeutic claims',
      'Using overly clinical or intimidating terminology',
      'Failing to visually convey the serene studio atmosphere',
    ],
  },

  ARTISAN: {
    id: 'base-artisan',
    industry: 'Artisanal & Craft Production',
    subindustries: [
      'Jewelry Crafting',
      'Woodworking & Custom Furniture',
      'Ceramics & Pottery',
      'Couture & Leathercraft',
      'Artisanal Soap & Cosmetics',
    ],
    businessModel: 'ARTISAN',
    typicalObjectives: [
      'Showcase craftsmanship quality and unique value',
      'Sell custom commissioned creations',
      'Build brand story and material provenance',
      'Justify fair artisan pricing',
    ],
    customerDecisionFactors: [
      'Uniqueness and artistic quality of the creation',
      'Authenticity of materials and handcraft technique',
      'Artisan values and creative story',
      'Customization possibilities',
      'Product durability and finish detail',
    ],
    trustDrivers: [
      'Behind-the-scenes workshop creation videos',
      'Transparent material sourcing and origin stories',
      'Detailed close-up photos of craftsmanship',
      'Customer reviews on custom order satisfaction',
    ],
    conversionActions: [
      'Custom project / commission enquiry',
      'Online shop purchase',
      'Workshop appointment or visit',
      'Newsletter subscription for limited product drops',
    ],
    contentPillars: [
      'Creation process & workshop moments',
      'Material selection & sourcing story',
      'Finished piece showcases & fine detail shots',
      'Artisan philosophy & creative inspiration',
    ],
    usefulProof: [
      'Time-lapse creation process videos',
      'Macro photography of finishes and textures',
      'Material origin and authenticity stories',
      'Client photos featuring custom pieces',
    ],
    commonObjections: [
      'Why is hand-crafted work more expensive than industrial items?',
      'How long does a custom order take to create?',
      'Can a creation be adapted to my specific request?',
      'How durable and long-lasting is the finished product?',
    ],
    seasonalFactors: [
      'End-of-year holiday gift shopping volume',
      'Artisan craft fairs and seasonal markets',
      'Wedding season for custom gifts and jewelry',
    ],
    localVisibilityImportance: 'MEDIUM',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Instagram',
      'Website',
      'Pinterest',
      'Facebook',
      'Email',
    ],
    usefulContentFormats: [
      'INSTAGRAM_REEL',
      'INSTAGRAM_CAROUSEL',
      'INSTAGRAM_POST',
      'WEBSITE_PAGE',
    ],
    strategicOpportunities: [
      'Document step-by-step creation processes in engaging short videos',
      'Offer limited-edition series or seasonal product drops',
      'Share the story behind rare or local raw materials',
    ],
    strategicRisks: [
      'Focusing only on finished items without showing the skill and effort involved',
      'Underpricing work by attempting to compete with industrial mass production',
      'Inconsistent client updates during long custom creation fulfillment',
    ],
  },

  OTHER: {
    id: 'base-other',
    industry: 'General Business Model',
    subindustries: [
      'Unclassified Industries',
      'Hybrid Business Models',
      'Specialized Niche Activities',
    ],
    businessModel: 'OTHER',
    typicalObjectives: [
      'Clarify the core value proposition for prospective customers',
      'Establish baseline brand trust and credibility',
      'Generate qualified customer enquiries or direct sales',
      'Test market interest in the offering',
    ],
    customerDecisionFactors: [
      'Clear understanding of what the offer actually includes',
      'Perceived value relative to requested price',
      'Trust in the provider’s capability',
      'Ease of taking the next engagement step',
    ],
    trustDrivers: [
      'Transparent explanations of products or services',
      'Customer or partner feedback and testimonials',
      'Clean and professional online presence',
      'Responsive and professional communication',
    ],
    conversionActions: [
      'Contact form submission',
      'Inquiry phone call or email',
      'Direct product or service purchase',
      'Newsletter or mailing list signup',
    ],
    contentPillars: [
      'Offer breakdown & value proposition',
      'Customer success stories & practical use cases',
      'Domain knowledge & educational insights',
      'Company story, values & background',
    ],
    usefulProof: [
      'Customer feedback, reviews & testimonials',
      'Product or service demonstrations',
      'Clear pricing tables or service process guides',
      'Certifications, credentials & partner badges',
    ],
    commonObjections: [
      'What exactly does this business offer and how does it help me?',
      'Is this offering suitable for my specific situation?',
      'What are the pricing and terms?',
      'How do I get started with this business?',
    ],
    seasonalFactors: [
      'General annual business planning cycles',
      'Q1 goal setting and initiative launches',
      'Q4 year-end project completion pushes',
    ],
    localVisibilityImportance: 'MEDIUM',
    seoImportance: 'MEDIUM',
    recommendedChannels: [
      'Website',
      'LinkedIn',
      'Instagram',
      'Google Business Profile',
      'Email',
    ],
    usefulContentFormats: [
      'WEBSITE_PAGE',
      'LINKEDIN_POST',
      'INSTAGRAM_POST',
      'BLOG_ARTICLE',
    ],
    strategicOpportunities: [
      'Focus on radical messaging clarity regarding the core customer problem solved',
      'Collect early customer feedback to continuously refine positioning',
      'Test different content formats to discover high-performing engagement angles',
    ],
    strategicRisks: [
      'Over-complicating the core value proposition for new prospects',
      'Spreading content marketing efforts across too many unaligned channels',
      'Failing to articulate a clear and compelling call to action',
    ],
  },
}

/**
 * Returns the foundational strategic playbook for a given business model.
 *
 * @param businessModel - The business model key
 * @returns The corresponding MuzaIndustryPlaybook
 */
export function getBaseIndustryPlaybook(
  businessModel: MuzaBusinessModel
): MuzaIndustryPlaybook {
  return MUZA_INDUSTRY_PLAYBOOKS[businessModel]
}
